### ISSUE TITLE
Part of lid sometimes appears on the corner of box in Explore screen

### ISSUE THREAD

**Issue by etwa4650** [phetsims/gas-properties#126] opened 2019-06-12 19:35 UTC
For https://github.com/phetsims/QA/issues/342

  <b>Operating System</b>

 Mac 10.4.5

  <b>Browser</b>

  Chrome 75.0.3770.80

  <b>Problem Description</b>

  In the Explore screen, if the lid has blown off, when you attempt to change the volume of the container with the lid still gone, sometimes the lid handle will appear in the top left corner of the container and spin around. The lid will fly away again once you stop dragging the container.

  <b>Steps to Reproduce</b>

  1: Go to "Explore" screen
  2: Pull container to maximum volume
  3: Fill container will maximum particles
  4: Drag the container, decreasing volume until the lid blows off
  5: Grab the container handle and decrease the container volume again
  6: You should see the lid reappear and spin in the top left corner of the container

  <b>Visuals</b>

https://drive.google.com/open?id=1-_E2T2SJbsxPmeVCV16TaFPjzYd9uSJ6

**Comment by arouinfar** [comment] 2019-06-12 20:10
Nice find @etwa4650!

@pixelzoom looks like this could be related to #93.

**Comment by pixelzoom** [comment] 2019-06-12 22:53
Cool. Definitely a bug.

**Comment by KatieWoe** [comment] 2019-06-12 22:55
This can be seen a bit easier on the intro screen since you can move the container when paused and use step through.

**Comment by pixelzoom** [comment] 2019-06-13 17:19
Reproduced with steps in https://github.com/phetsims/gas-properties/issues/126#issue-455387636, but in Ideal screen.   

Typically, resizing the container causes the lid size to be adjusted.  This should be skipped when the lid is off the container.   That's currently not the case, and it's what's causing the problem.

**Comment by pixelzoom** [comment] 2019-06-13 17:25
Fixed in master. @etwa4650 please verify.  If it looks OK, please change this issue to "status:fixed-awaiting-deploy".

**Comment by pixelzoom** [comment] 2019-06-13 18:42
Looks like you reviewed @etwa4650. Thanks.

**Comment by KatieWoe** [comment] 2019-07-31 20:47
Looks good 1.0.0-rc.1.  Was a bit complicated by https://github.com/phetsims/gas-properties/issues/151, but that is now fixed in master

**Closed by KatieWoe** 2019-07-31 20:47 UTC
Labels: status:ready-for-qa, type:bug
