### ISSUE TITLE
CT mismatched index, possible start/end mismatch

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#217] opened 2024-03-19 15:49 UTC
Also in Intro
```
gas-properties : phet-io-state-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/phet-io-wrappers/state/?sim=gas-properties&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1710812431988%22%2C%22timestamp%22%3A1710812879527%7D
Uncaught Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/assert/js/assert.js:28:13)
at assert (dataStream.ts:299:14)
at end (PhetioObject.ts:514:29)
at phetioEndEvent (phetioCommandProcessor.ts:254:17)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1710812431988%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dgas-properties%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1710812431988%22%2C%22timestamp%22%3A1710812879527%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1710812431988%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dgas-properties%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1710812431988%22%2C%22timestamp%22%3A1710812879527%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/phet-io-wrappers/state/?sim=gas-properties&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1710812431988%22%2C%22timestamp%22%3A1710812879527%7D
[ATTACHED]
[NAVIGATED] about:blank
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&ea&postMessageOnError&sim=gas-properties&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1710812431988%22%2C%22timestamp%22%3A1710812879527%7D&frameTitle=source
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&ea&postMessageOnError&sim=gas-properties&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1710812431988%22%2C%22timestamp%22%3A1710812879527%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: accessed value outside of dependency tracking
[CONSOLE] Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
[PAGE ERROR] Error: Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/assert/js/assert.js:28:13)
at DataStream.end (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/phet-io/js/dataStream.js:253:15)
at PhetioCommandProcessor.phetioEndEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/tandem/js/PhetioObject.js:439:30)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:135:18
[PAGE ERROR] Error: Error: Assertion failed: accessed value outside of dependency tracking
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/assert/js/assert.js:28:13)
at DerivedProperty.get (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/ReadOnlyProperty.js:168:19)
at DerivedProperty.equalsValue (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/ReadOnlyProperty.js:219:44)
at DerivedProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/ReadOnlyProperty.js:199:24)
at DerivedProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/ReadOnlyProperty.js:187:12)
at DerivedProperty.getDerivedPropertyListener (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/DerivedProperty.js:121:13)
at TinyStaticProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/TinyEmitter.js:99:9)
at TinyStaticProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/TinyStaticProperty.js:49:10)
at CollisionCounterNode.validateBounds (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/scenery/js/nodes/Node.js:1349:31)
at TinyStaticProperty.get (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/TinyStaticProperty.js:26:10)
[PAGE ERROR] Error: Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/assert/js/assert.js:28:13)
at DataStream.end (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/phet-io/js/dataStream.js:253:15)
at PhetioCommandProcessor.phetioEndEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/tandem/js/PhetioObject.js:439:30)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:135:18
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 3/18/2024, 7:40:31 PM

----------------------------------

gas-properties : phet-io-wrappers-tests : assert
Tried to run 3 times, never completed, failure: Error: Error: Did not get next-test message in 400000ms (currentSendingCount 0): ["gas-properties","phet-io-wrappers-tests","assert"]
[URL] http://128.138.93.172/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1710812431988%2Fphet-io-wrappers%2Fphet-io-wrappers-tests.html%3Fsim%3Dgas-properties%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue&duration=600000&testInfo=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-wrappers-tests%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710812431988%22%2C%22timestamp%22%3A1710813009706%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1710812431988%2Fphet-io-wrappers%2Fphet-io-wrappers-tests.html%3Fsim%3Dgas-properties%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue&duration=600000&testInfo=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-wrappers-tests%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710812431988%22%2C%22timestamp%22%3A1710813009706%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/phet-io-wrappers/phet-io-wrappers-tests.html?sim=gas-properties&phetioDebug=true&phetioWrapperDebug=true
[CONSOLE] Failed to load resource: the server responded with a status of 404 (Not Found): http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/phet-io-wrappers/phet-io-wrappers-strings_en.json
[CONSOLE] enabling assert
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&postMessageOnError&sim=gas-properties&phetioDebug=true&phetioWrapperDebug=true&ea
[CONSOLE] enabling assert
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&postMessageOnError&sim=gas-properties&phetioDebug=true&phetioWrapperDebug=true&ea
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] Deprecation warning: launchSim is deprecated, use launchSimulation instead.
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&postMessageOnError&sim=gas-properties&phetioDebug=true&phetioWrapperDebug=true&ea
[CONSOLE] enabling assert
[CONSOLE] Deprecation warning: getStateForObject is deprecated, use getPhetioElementState instead.
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&postMessageOnError&sim=gas-properties&phetioDebug=true&phetioWrapperDebug=true&ea
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&ea&postMessageOnError&sim=gas-properties&phetioDebug=true&phetioWrapperDebug=true&fuzz
[CONSOLE] enabling assert
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&ea&postMessageOnError&sim=gas-properties&phetioDebug=true&phetioWrapperDebug=true&fuzz
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&ea&postMessageOnError
[CONSOLE] enabling assert
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&ea&postMessageOnError
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&ea&postMessageOnError
[CONSOLE] enabling assert
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&ea&postMessageOnError
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&ea&postMessageOnError
[CONSOLE] enabling assert
[CONSOLE] Assertion failed: args should be an array
[CONSOLE] Assertion failed: callback should be a function
[CONSOLE] Error from phetioClient JSHandle@error
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&ea&postMessageOnError
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&ea&postMessageOnError
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/phet-io-wrappers/phet-io-wrappers-tests.html?sim=gas-properties&phetioDebug=true&phetioWrapperDebug=true&phetioClientName=NewSpecialClientName
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/phet-io-wrappers/phet-io-wrappers-tests.html?sim=gas-properties&phetioDebug=true&phetioWrapperDebug=true
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&ea&postMessageOnError
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/gas-properties/gas-properties_en.html?brand=phet-io&ea&postMessageOnError&locales=*
[CONSOLE] enabling assert
[CONSOLE] Assertion failed: accessed value outside of dependency tracking
[CONSOLE] Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
[PAGE ERROR] Error: Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/assert/js/assert.js:28:13)
at DataStream.end (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/phet-io/js/dataStream.js:253:15)
at PhetioCommandProcessor.phetioEndEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/tandem/js/PhetioObject.js:439:30)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:135:18
[PAGE ERROR] Error: Error: Assertion failed: accessed value outside of dependency tracking
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/assert/js/assert.js:28:13)
at DerivedProperty.get (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/ReadOnlyProperty.js:168:19)
at DerivedProperty.equalsValue (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/ReadOnlyProperty.js:219:44)
at DerivedProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/ReadOnlyProperty.js:199:24)
at DerivedProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/ReadOnlyProperty.js:187:12)
at DerivedProperty.getDerivedPropertyListener (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/DerivedProperty.js:121:13)
at TinyStaticProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/TinyEmitter.js:99:9)
at TinyStaticProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/TinyStaticProperty.js:49:10)
at Text.validateBounds (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/scenery/js/nodes/Node.js:1349:31)
at TinyStaticProperty.get (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/axon/js/TinyStaticProperty.js:26:10)
[PAGE ERROR] Error: Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/assert/js/assert.js:28:13)
at DataStream.end (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/phet-io/js/dataStream.js:253:15)
at PhetioCommandProcessor.phetioEndEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/tandem/js/PhetioObject.js:439:30)
at http://128.138.93.172/continuous-testing/ct-snapshots/1710812431988/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:135:18
Error: Did not get next-test message in 400000ms (currentSendingCount 0): ["gas-properties","phet-io-wrappers-tests","assert"]

id: "Sparky Node Puppeteer"
Snapshot from 3/18/2024, 7:40:31 PM
```

**Comment by zepumph** [comment] 2024-03-19 16:05
@pixelzoom asked for help in parsing what this assertion error means. It is a misnomer, as actually the error is upstream from this assertion. 

This assertion is a result of the async nature of PhET-iO communicating across an iframe, and often this is the error that CT catches, even though the actual error occurred before this one. So basically when you see an assertion like this (or any assertion on CT), it is a good idea to glance through the console output from the CT message. That will tell you the desired information.


For the above, it looks like the assertion that happened right before the mismatched index error was this:

```
[CONSOLE] Assertion failed: accessed value outside of dependency tracking
```


Continued details about the mismatched index error below. Let me know if you'd like to discuss further.

<details>

This assertion occurs when the wrapper doesn't receive the correct next message from the sim (by index). So the next message to process of `n`, and the wrapper got a batch of messages from the sim in which all of them had an index greater than `n`. Here `n` got lost because while trying to send it back, and assertion occurred, so it never sent message `n`. Since the sim is in an iframe, there are some cases where an error in that frame will not cascade of to CT, but instead will try to be handled by PhET-iO, but where that fails critically (like with assertions), we fail out, breaking the wrapper communication layer.

**Comment by pixelzoom** [comment] 2024-03-19 16:31
Reproduced with http://localhost:8080/phet-io-wrappers/state/?sim=gas-properties&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&debugger&audio=disabled

**Comment by pixelzoom** [comment] 2024-03-19 16:57
Worked on this with @zepumph -- thanks!  Fixed in https://github.com/phetsims/gas-properties/commit/1ed734b25675cc413acc29ea758a02e5e47716b6 (ignore https://github.com/phetsims/gas-properties/commit/1ed734b25675cc413acc29ea758a02e5e47716b6).

I've been bitten by this problem before, will probably be bitten again.  Using ScreenView visibleProperty as a dependency creates weird problems with the `strictAxonDependencies` features.  If you use visibleProperty as a dependency, you typically need to add `strictAxonDependencies: false`.   @samreid FYI.

I'll wait a couple of CT cycles before closing.

**Comment by pixelzoom** [comment] 2024-03-19 18:31
CT is happy. Closing.

**Closed by pixelzoom** 2024-03-19 18:31 UTC
Labels: type:automated-testing
