### ISSUE TITLE
Temperature is not held constant when N decreases

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#159] opened 2019-08-02 22:10 UTC
**Test device**
Dell Laptop
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/392 and https://github.com/phetsims/QA/issues/390
When temperature is set to be held constant, this does not occur when particles are leaving the container.
From slack:
>I’m going to say it’s a bug, and create an issue. I would think that T should stay constant, P should change,

**Steps to reproduce**
1. Add some particles
2. Set temperature to be constant
3. Open the lid and allow particles to leave

**Visuals**
![notconstant](https://user-images.githubusercontent.com/41024075/62401326-fc2ebf80-b53f-11e9-9258-af23c6c737f6.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gases Intro‬
URL: https://phet-dev.colorado.edu/html/gases-intro/1.0.0-rc.2/phet/gases-intro_all_phet.html
Version: 1.0.0-rc.2 2019-08-01 00:48:25 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment] 2019-08-02 22:17
I can see why we didn’t notice this sooner.  When the lid is closed, particles are added with initial speed based on the temperature in the container, so `T` remains constant without doing anything special in the model.  

But when the lid is _open_, particles escape from the container.  So to keep `T` constant, we need to adjust the speeds of particles in the containers so that `KE` average results in the desired (constant) `T`.  

Relevant equations: 
* T = (2/3)KE/k 
* KE = (1/2)m|v|<sup>2</sup>

In `IdealGasLawModel.compensateForHoldConstant`, I’ll need to add an `else-if` block:

```js
else if ( this.holdConstantProperty.value === HoldConstant.TEMPERATURE ) {
  // adjust particle speeds to result in constant T
}
```

And there may be some additional code needed when `N` becomes zero, to show the dialog with "Oops! Temperature cannot be held constant when the container is empty."

**Comment by pixelzoom** [comment] 2019-08-02 22:18
@arouinfar please verify that my evaluation in https://github.com/phetsims/gas-properties/issues/159#issuecomment-517859650 looks reasonable/correct.

**Comment by KatieWoe** [comment] 2019-08-02 22:43
Quick note.  If you remove particles using the back arrows temperature is also not held constant

**Comment by pixelzoom** [comment] 2019-08-02 22:56
Thanks @KatieWoe, good catch.

**Comment by pixelzoom** [comment] 2019-08-02 22:58
Since adjusting particle speeds is like to be a significant performance hit for large `N`, I may consider doing this only when `N` has decreased.  I.e.:

**Comment by pixelzoom** [comment] 2019-08-05 17:44
This is a little complicated, because KE is a function of |v|<sup>2</sup>.  Here's what I think is needs to be done when N decreases when holding T constant.   I'll need @arouinfar to review.

```js
// compute the desired average KE that will result in T
desireAverageKE = (3/2)Tk

// compute the KE scale
scale = desireAverageKE / actualAverageKE

// for each particle...
|v| = Math.sqrt( 2 * actualKE * scale / m )
```

**Comment by pixelzoom** [comment] 2019-08-05 18:06
@arouinfar and I discussed https://github.com/phetsims/gas-properties/issues/159#issuecomment-518330915 via Zoom, and reviewed my implementation of it.  Seems to be correct, so I'll proceed.

**Comment by pixelzoom** [comment] 2019-08-05 18:09
Fixed in master and 1.0 branches.  @KatieWoe and @arouinfar please review in master.

**Comment by KatieWoe** [comment] 2019-08-05 18:19
Seems to work in master.  There did seem to be a performance hit with large numbers of particles.  I also think that, since the solution involves speeding up remaining particles, the heat bucket should activate for a bit to indicate that.

**Comment by pixelzoom** [comment] 2019-08-05 18:47
@KatieWoe please describe steps to reproduce the performance hit mentioned in the previous comment.

**Comment by pixelzoom** [comment] 2019-08-05 18:49
@arouinfar please comment on @KatieWoe's suggestion about the heat/cool bucket in https://github.com/phetsims/gas-properties/issues/159#issuecomment-518343285.

**Comment by KatieWoe** [comment] 2019-08-05 18:52
I was on the first screen and noticed the slow down as I pumped the container full of blue particles and switched to keeping temperature constant

**Comment by pixelzoom** [comment] 2019-08-05 18:57
@KatieWoe Nothing that you did in those steps hits the code that I added to address this issue.  The new code is only exercised when the number of particles is reduced.  I added debugging output to confirm that before I pushed, and I've confirmed it again.

**Comment by pixelzoom** [comment] 2019-08-05 19:13
@arouinfar and I discussed the heat/cool bucket via Zoom.  According to @arouinfar, there should be no heating/cooling if N is changed via the spinners.  But if particles escape via the lid, then there should be heating/cooling via the bucket, using the same "Hollywood" feedback was done for "Pressure T" mode.

Getting this to work is going to be a much bigger problem than adjusting particle speeds to keep T constant.  The part of the model that deals with this has no idea of _why_ N changed.

**Comment by pixelzoom** [comment] 2019-08-05 19:16
@arouinfar the design doc shows no change to heat/cool buck for "Temperature (T)" mode, so please verify that this is really what needs to be done.

<img width="661" alt="screenshot_1300" src="https://user-images.githubusercontent.com/3046552/62489127-350aa680-b783-11e9-870a-49472cc6c90a.png">

**Comment by KatieWoe** [comment] 2019-08-05 19:19
All the same, it can be quite noticeable that remaining particles are "magically" speeding up if N is low, which could be pedagogically damaging.

**Comment by pixelzoom** [comment] 2019-08-05 19:22
@KatieWoe please clarify - are you arguing that we should be applying heat/cool regardless of how N decreased, not just as the result of escaping through the lid?

**Comment by KatieWoe** [comment] 2019-08-05 19:39
I think that would be most ideal, but not necessary, since they are leaving magically, they can probably change energy magically.  But, I do think it is definitely necessary if they leave from the top.

**Comment by arouinfar** [comment] 2019-08-05 20:11
> there should be no heating/cooling if N is changed via the spinners. But if particles escape via the lid, then there should be heating/cooling via the bucket, using the same "Hollywood" feedback was done for "Pressure T" mode

Before this zoom chat, @kathy-phet and I briefly talked about this issue, and mutually decided that this approach would be the way to go.

> the design doc shows no change to heat/cool buck for "Temperature (T)" mode, so please verify that this is really what needs to be done.

@pixelzoom that table shows that the HeaterCoolerNode slider is removed. I didn't have adjust velocities in the change N column because we hadn't considered <i>how</i> T was held constant, which was an oversight. 

> I think that would be most ideal, but not necessary, since they are leaving magically, they can probably change energy magically. But, I do think it is definitely necessary if they leave from the top.

When removing particles with the spinners, the temperature can either increase or decrease, depending on which particles happen to be removed (last in, first out). This fluctuation in temperature is not physical (like evaporative cooling) so it seems very strange to explicitly show heat being added/removed. With the lid open (evaporative cooling) the most energetic particles are leaving, bringing down the average velocity. To maintain constant T, we would need to add heat to the particles left behind.

**Comment by pixelzoom** [comment] 2019-08-06 17:00
More problems...

* The animated heat/cool bucket is not reusable for "Temperature (T)" mode.  It was designed implemented explicitly for "Pressure T" mode, where the amount of flame/ice shown is a function of N and delta T.

* Particles can escape through the lid _and_ be decreased using the spinners on the same timestep.  The amount of heat/ice shown show presumably be related only to the particles that escape through the lid.  But this is currently impossible, because there's nothing that keeps track of _how_ the number of particles was decreased.

**Comment by pixelzoom** [comment] 2019-08-06 17:32
@arouinfar and I discussed on Slack.  Given the problems that I'm running into, we are reconsidering whether we need to counteract evaporative cooling - that is, keeping T constant while particles are escaping via the lid.   Here's the alternative proposal:

* When the lid is open, disable the "Temperature (T)" radio button
* When "Temperature (T)" radio button is selected, either 
  (a) hide the lid handle, or
  (b) when the lid handle is grabbed, show dialog "Oops! Temperature cannot be held constant when the lid is open." and change Hold Constant to "None"

Also note that if evaporative cooling is a learning goal, then we are showing that in modes where T is not held constant.  What we would be dropping here is _counteracting_ evaporative cooling.

**Comment by KatieWoe** [comment] 2019-08-06 17:39
In regards to a).  What would happen if the lid was open or blown off already?

**Comment by pixelzoom** [comment] 2019-08-06 17:54
If the lid is open, then you can't select "Temperature (T)" because it's disabled.

If the lid blows off, then we could show the Oops dialog.  @arouinfar and I are both leaning towards (b) as the preferred choice, and handling the lid blowing off is another reason for that choice.

**Comment by pixelzoom** [comment] 2019-08-06 18:01
So here's the revised proposal:

* When the lid is open, disable the "Temperature (T)" radio button
* When the lid is removed for any reason (by the user, blown off), show dialog "Oops! Temperature cannot be held constant when the lid is open." and change Hold Constant to "None"

**Comment by pixelzoom** [comment] 2019-08-06 19:26
I'm running into a problem with the above proposal.  When the user starts to interact with the lid, the Oops dialog immediate opens and the "Nothing" becomes selected.  But the lid is open such a small amount that it doesn't look like it's open.   And trying to make it look "more open" leads to a reentrant Property problem, which will cause PhET-iO problems. 

So here's a revised proposal:
* When the lid is open, disable the "Temperature (T)" radio button
* When "Temperature (T)" is selected, hide the handle on the lid
* When the lid is blown off, show dialog "Oops! Temperature cannot be held constant when the lid is open." and change Hold Constant to "None"

**Comment by pixelzoom** [comment] 2019-08-06 19:47
I have implemented the proposal described in https://github.com/phetsims/gas-properties/issues/159#issuecomment-518809409, and it's working nicely.  It involves minimal/isolated changes to 9 files, and no architectural changes, so I'm confident that it will not destabilize the sim.  I will not commit it until the proposal is approved.

**Comment by kathy-phet** [comment] 2019-08-07 02:26
This seems like a reasonable approach to me, thanks! But note I haven’t played with master to see the new changes, just read the thread.

Sent from my iPhone

On Aug 6, 2019, at 1:47 PM, Chris Malley <notifications@github.com<mailto:notifications@github.com>> wrote:


I have implemented the proposal described in #159 (comment)<https://github.com/phetsims/gas-properties/issues/159#issuecomment-518809409>, and it's working nicely. It involves minimal/isolated changes to 9 files, and no architectural changes, so I'm confident that it will not destabilize the sim. I will not commit it until the proposal is approved.

**Comment by pixelzoom** [comment] 2019-08-07 15:11
I went ahead and pushed this change.   It behaves as described in https://github.com/phetsims/gas-properties/issues/159#issuecomment-518809409. 

@arouinfar @KatieWoe please review in master.

**Comment by KatieWoe** [comment] 2019-08-07 15:39
Looks good on master

**Comment by arouinfar** [comment] 2019-08-07 19:57
Thanks @pixelzoom. Master is looking good to me.

**Comment by pixelzoom** [comment] 2019-08-07 20:37
To be verified in 1.0.0-rc.3.

**Comment by pixelzoom** [comment] 2019-08-08 21:51
I realized that commit 4de909f9033588b2db6d13550ef389f83018b18a duplicates a bunch of code that was already in place to solve the problem or adjusting particle speeds to match a specific temperature.   So I have replaced most of that commit with the above commit (in master and 1.0 branches).

@arouinfar and @KatieWoe sorry to ask you to do this, but please verify again.

**Comment by arouinfar** [comment] 2019-08-08 22:06
Master is still looking good to me @pixelzoom.

**Comment by pixelzoom** [comment] 2019-08-08 22:37
I see that @KatieWoe is out this afternoon.  So I'm going to move forward, and she can verify this in 1.0.0-rc.3.

**Comment by lmulhall-phet** [comment] 2019-08-09 18:19
The behavior described in https://github.com/phetsims/gas-properties/issues/159#issuecomment-518809409 looks good in 1.0.0-rc.3.

**Closed** 2019-08-12 21:44 UTC
Labels: status:ready-for-qa, type:bug
