### ISSUE TITLE
Particles can be permanently stuck in container; Temperature can be infinitely increased

### ISSUE THREAD

**Issue by etwa4650** [phetsims/gas-properties#128] opened 2019-06-12 20:58 UTC
For https://github.com/phetsims/QA/issues/342

  <b>Operating System</b>

Mac OS 10.14.5

  <b>Browser</b>

Chrome 75.0.3770.80 

  <b>Problem Description</b>

  Following the steps below, you can create a situation in which particles are trapped in the container, which allows you to infinitely raise temperature and pressure. With a high enough temperature you can then release all particles into the container so that they are all stuck.

  <b>Steps to Reproduce</b>

 1: Go to the "Ideal" screen
 2: Expand the container to its maximum size
 3: Release 1 "Light" particle into the container
 4: Increase the temperature until max pressure (make sure lid does not blow off) [CM: 1:05 in video]
 5: Pause the sim
 6: Decrease the volume of container to the minimum
 7: Release all of the particles into container, both Heavy and Light
 8: Resume the sim
 9: Wait until most particles have left the container
 10: At this point you should see a few Light particles that are stuck
 11: You can now raise the temperature without limit
 12: After a certain temperature, any particle added will also be stuck in the container [CM: 2:11 in video]

  <b>Visuals</b>

Video of full setup and resutls:

https://drive.google.com/open?id=1T_p1jm2l372Ob_lO-xggFTWddUqmfv_G

**Comment by pixelzoom** [comment] 2019-06-12 22:58
Thanks for finding this. There's some weird stuff in that video, I'll investigate.

**Comment by arouinfar** [comment] 2019-06-12 23:00
@pixelzoom I'm not entirely sure if this is a bug or not. Seems to me like an interesting edge case, but still worth looking into.

**Comment by pixelzoom** [comment] 2019-06-13 22:16
@arouinfar Most of this seems explainable to me. I see how the temperature can get huge with a single particle.  And I can see how a particle can get stuck bouncing between the top and bottom walls of the container.  What I don't understand is what happens at 2:11 in the video, where a bunch of particles are added and they all get stuck bouncing between the top and bottom walls of the container.  Do you have an explanation or hypothesis?

**Comment by arouinfar** [comment] 2019-06-14 19:40
> What I don't understand is what happens at 2:11 in the video, where a bunch of particles are added and they all get stuck oscillating between the top and bottom walls of the container. Do you have an explanation or hypothesis?

Thanks @pixelzoom. When talking about this issue with @etwa4650, I had seen the particles get stuck vertically oscillating at very high temps, but I hadn't seen the 2:11 behavior before. That certainly looks buggy, but I'm not sure how I could explain it. 

@ariel-phet can you take a look at this issue?

**Comment by pixelzoom** [comment] 2019-06-14 19:47
Perhaps it's related to the extreme temperature.  But I don't see how particles would immediate oscillate when they are added to the container.  The range of the initial velocity angle shouldn't permit that.

**Comment by arouinfar** [comment] 2019-06-14 19:55
> Perhaps it's related to the extreme temperature. But I don't see how particles would immediate oscillate when they are added to the container. The range of the initial velocity angle shouldn't permit that.

Exactly my thoughts @pixelzoom.

**Comment by pixelzoom** [comment] 2019-06-14 22:31
I'm having a really difficult time reproducing this.  When I get to step 4 (blow the lid off), the single particle is going so fast that it exits the container through the lid before I can do step 5 (pause the sim). So the container becomes empty, pressure drops to zero, and there is no temperature.

**Comment by pixelzoom** [comment] 2019-06-15 20:06
I'm having a really difficult time reproducing this. When I get to step 4 (blow the lid off), the single particle is going so fast that it exits the container through the lid before I can do step 5 (pause the sim). So the container becomes empty, pressure drops to zero, there is no temperature, and the remaining steps don't work.

@etwa4650 any tips on how to get past step 4?

**Comment by etwa4650** [comment] 2019-06-16 21:47
@pixelzoom Do not blow off the lid, raise the temperature as high as you can without blowing off the lid then you can pause.

**Comment by pixelzoom** [comment] 2019-06-16 22:14
Ah, thanks @etwa4650.  You even said that in your description - "(make sure lid does not blow off)".

**Comment by pixelzoom** [comment] 2019-06-17 01:59
Reproduced in 1.3.0-rc.1 and in master.  I'm can't explain this and I'm not sure what to do about it.  It seems like emergent behavior of the particle system, where some particles can get stuck oscillating between parallel walls (top/bottom or left/right).

@arouinfar @ariel-phet suggestions?

**Comment by pixelzoom** [comment] 2019-06-17 02:01
Reproduced in 1.3.0-rc.1 and in master.  I'm can't explain this and I'm not sure what to do about it.  I suspect that it's emergent behavior of the particle system, where some particles can get stuck oscillating between parallel walls (top/bottom or left/right), and won't collide with anything but the walls because their speed is so high that they will never intersect other particles.

@arouinfar @ariel-phet suggestions?

**Comment by arouinfar** [comment] 2019-06-17 17:41
>  1.3.0-rc.1

I'm assuming you meant dev.38 or dev.39. :)

>  I'm can't explain this and I'm not sure what to do about it

Ditto. I can't come up with a reasonable explanation for the 2:11 behavior since incoming particles would have a variety of velocity directions.

That said, it seems like enough of an edge case that I'd be comfortable with deferring this issue, but let's see what @ariel-phet has to say.

**Comment by pixelzoom** [comment] 2019-06-17 17:54
> > 1.3.0-rc.1
> I'm assuming you meant dev.38 or dev.39. :)

1.0.0-dev.38  (Sorry,  1.3.0-rc.1 is ph-scale, which I'm working on at the same time.)

**Comment by pixelzoom** [comment] 2019-06-17 18:03
The only thing that I can think of is a workaround that goes something like this:  When a particle collides with a wall, detect whether it had collided with the opposite (parallel) wall on the previous time step.  If it had, then make a small random adjustment to its velocity angle.  Hopefully this would break up the oscillation.  No idea how difficult this would be, or what impact on performance it might have.

**Comment by ariel-phet** [comment] 2019-06-19 03:28
@pixelzoom @arouinfar this issue makes me think we should have a new label that is something like "nominated for the @phet-steele memorial prize for bug identification" and at the end of the year we collect such bugs, and actually award the prize (maybe Steele has ideas for the award...)

But more seriously, awesome work @etwa4650 in identifying and giving reproducible steps, pretty impressive!

I actually don't think this is a bug exactly. What I am seeing is that with the flood of particles and the extreme temperature a particle or two basically have only vertical velocity (so they are "stuck" in the container because they are purely vertically moving). Maybe @pixelzoom the hard sphere collision model has some threshold to impart x vs y velocity depending on the collision.

Anyhow, when you release the flood of particles, my guess is that the oscillating particle hits them so fast that it makes them all also go vertically. We see that light particle moving, but my guess is its speed is insane (my quick calculation assuming light particle is helium is 1.5x10^6 m/s)

I am definitely fine deferring - We could also put a cap on the temperature (through in an oops dialogy like "max temp" reached) as my guess is that would allow this behavior not to happen.

**Comment by ariel-phet** [comment] 2019-06-19 03:29
Assigning to @pixelzoom if he also wants to just close or discuss an oops dialog solution

**Comment by pixelzoom** [comment] 2019-06-21 14:45
I suggested the workaround in https://github.com/phetsims/gas-properties/issues/128#issuecomment-502789824.

@ariel-phet suggested:
> Maybe @pixelzoom the hard sphere collision model has some threshold to impart x vs y velocity depending on the collision.

@ariel-phet also suggested:
> We could also put a cap on the temperature (through in an oops dialogy like "max temp" reached) as my guess is that would allow this behavior not to happen.

@arouinfar do you have any preference here?

**Comment by pixelzoom** [comment] 2019-06-26 02:03
I'm not too keen about the options that involve a non-physical workaround, I think they could get us into trouble in other ways.  So I'm leaning towards putting a cap on temperature, with an Oops dialog.  But I'm not sure what a reasonable cap would be (100000 K?), what the message should say, and what should happen as a result.  @ariel-phet @arouinfar thoughts?

**Comment by arouinfar** [comment] 2019-06-26 21:29
@pixelzoom @ariel-phet I would rather not to mess with the physics, so I'd also prefer an Oops dialog. I think 100000 K seems like a reasonable cap, and I think we'd want to to reset the container which I think would include:
* Clearing all particles from the container (like erase button)
* Returning lid (if off)
* Setting Hold Constant to Nothing (necessary since we're emptying the container)

I think the Oops dialog could read something like:
```
Oops!

Maximum temperature reached.
```

How does that sound @ariel-phet @pixelzoom?

**Comment by pixelzoom** [comment] 2019-06-26 23:44
Sounds reasonable to me.

**Comment by pixelzoom** [comment] 2019-06-27 02:07
Since @ariel-phet is out for a bit, I took the liberty of proceeding with @arouinfar's suggestion in https://github.com/phetsims/gas-properties/issues/128#issuecomment-506052574.   

Here's what has been added to master:

* `maxTemperature` query parameter, default `100000` K.  Use this to more quickly reach the maximum temperature, or to fine-tune the default value.

* When `maxTemperature` is reached:
(1) All particles are deleted, inside and outside the container.
(2) If Hold Constant has a value other than "Nothing" or "Volume", it is set to "Nothing". (We can't unilaterally set to "Nothing" because "Volume" is required by the Energy screen.)
(3) If the lid is off of the container, it is returned.
(4) The Oops dialog shown below is displayed.

@arouinfar please review in master.

<img width="559" alt="screenshot_1260" src="https://user-images.githubusercontent.com/3046552/60227661-2cf34900-985e-11e9-902b-ee8bde7cf2e4.png">

**Comment by arouinfar** [comment] 2019-06-27 18:55
@pixelzoom this is all looking really nice in master. I think a `maxTemperature` of 100000 is sufficiently large that most students will never encounter the dialog, but still low enough to avoid the buggy-looking behavior originally reported by @etwa4650.

**Comment by pixelzoom** [comment] 2019-06-27 23:22
Thanks @arouinfar. 

Since @ariel-phet suggested this approach, I doubt that he'll have an issue with it, though he may have suggestion on specific.  So @ariel-phet please weigh in before this goes back to QA for verification.

**Comment by ariel-phet** [comment] 2019-06-30 18:19
@pixelzoom @arouinfar all seems good to me

**Comment by KatieWoe** [comment] 2019-07-29 22:18
Warning dialog comes up as expected from what I've seen.  Tried this when temp reached close to max, and the bug didn't seem to occur.  Will close after playing around trying to break the solution a bit more, but for now it looks good.

**Closed** 2019-07-31 20:49 UTC
Labels: design:general, status:ready-for-qa, type:bug
