### ISSUE TITLE
Sim doesn't launch with correct avg temperature if mass is changed on Diffusion Screen

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gas-properties#284] opened 2024-07-15 20:38 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1107, in the Studio and State wrappers on the Diffusion Screen changing the Mass of either particle type will result in an incorrect Tavg in the Data Panel when the sim is launched. 

**Steps to reproduce**
1. In Studio go to the Diffusion screen
2. Open the Data Panel
3. Add 20 Red Particles
4. Change the Mass to 30
5. Press Test

**Visuals**
<img width="978" alt="Screenshot 2024-07-15 at 4 37 01 PM" src="https://github.com/user-attachments/assets/0842c382-2d48-476c-8394-1d944fdd2a5a">
<img width="1271" alt="Screenshot 2024-07-15 at 4 37 21 PM" src="https://github.com/user-attachments/assets/8c38f150-52f9-4a66-a428-7a35f5390a3b">

**Comment by pixelzoom** [comment] 2024-07-15 23:09
Reproduced in main, very weird. T<sub>avg</sub> should be the same as the Initial Temperature setting.  In the launched sim, if I change Initial Temperature to 250, then back to 300, then T<sub>avg</sub> is correct.   I'm guessing there's an ordering issue with how state is restored that is resulting in a different result.

**Comment by pixelzoom** [comment] 2024-07-16 00:02
In the above commits, I tightened up the API for DiffusionData, which is where `averageTemperatureProperty` lives and is computed.

**Comment by pixelzoom** [comment] 2024-07-16 00:10
Adding this to DiffusionModel's constructor resolves the problem.  But I don't think this should be necessary, because `stepModelTime` should be calling this.

```ts
    if ( assert && Tandem.PHET_IO_ENABLED ) {
      phet.phetio.phetioEngine.phetioStateEngine.stateSetEmitter.addListener( () => this.updateData() );
    }
```

**Comment by pixelzoom** [comment] 2024-07-16 19:52
I am very confused. After the DiffusionData changes in https://github.com/phetsims/diffusion/commit/4b0cea401b839cc012668a79eb43937b8dc75478, I can no longer reproduce the problem. But that changed nothing about how or when `averageTemperatureProperty` is computed.

**Comment by pixelzoom** [comment] 2024-07-16 20:39
If I omit step 4 (Change the Mass to 30) then Tavg is correct.

**Comment by pixelzoom** [comment] 2024-07-16 21:03
Inspecting `totalKE` computed by DiffusionData `update`...  With the sim running in Studio, the `totalKE` is `74844000`.  In the Standard wrapper, it's `69854400`.  Since `KE = (1/2) * m * |v|^2` (see Particle `getKineticEnergy`) this suggests that the mass (m) or speed (|v|) is incorrect in the State wrapper.

**Comment by pixelzoom** [comment] 2024-07-16 21:09
DiffusionParticle extends Particle, and adds `mass` and `radius` fields.  While ParticleIO exists for serializing Particle, we do not currently have DiffusionParticleIO.  So the mass and radius fields are not being serialized, and will be incorrect until something occurs in the Standard wrapper (or Downstream sim) to update mass and radius.

Ugh... This will be a big change.

**Comment by pixelzoom** [comment] 2024-07-16 21:17
Looking more closely at ParticleStateObject, I see that it does include `mass` and `radius`:

```ts
export type ParticleStateObject = {
  mass: number;
  radius: number;
  x: number;
  y: number;
  _previousX: number;
  _previousY: number;
  vx: number;
  vy: number;
};
```

The difference with DiffusionParticle is that mass and radius are mutable.  So something is apparently not setting mass (and radius?) when restoring the state of DiffusionParticle instances.

**Comment by pixelzoom** [comment] 2024-07-16 21:19
The problem is in DiffusionParticleSystem, where there's some overly-zealous use of `isSettingPhetioStateProperty` that is preventing mass, speed, and radius from being set; see below.  Removing these guards should fix the problem, with no need for DiffusionParticleIO.

```ts
   Multilink.multilink(
      [ this.particle2Settings.massProperty, this.particle2Settings.initialTemperatureProperty ],
      ( mass, initialTemperature ) => {
        if ( !isSettingPhetioStateProperty.value ) {
          updateMassAndSpeed( mass, initialTemperature, this.particles2 );
        }
      } );

    // Update radii of existing particles.
    this.particle1Settings.radiusProperty.link( radius => {
      if ( !isSettingPhetioStateProperty.value ) {
        updateRadius( radius, this.particles1, container.leftBounds, isPlayingProperty.value );
      }
    } );
    this.particle2Settings.radiusProperty.link( radius => {
      if ( !isSettingPhetioStateProperty.value ) {
        updateRadius( radius, this.particles2, container.rightBounds, isPlayingProperty.value );
      }
    } );
```

**Comment by pixelzoom** [comment] 2024-07-16 21:56
The fix is https://github.com/phetsims/gas-properties/commit/470663f44ee3362a46958ad558d30fdb21aad002, the other commits are patches for the 3 sim branches. 

@Nancy-Salpepi please test in main. Leave open for verification in 1.1.0-rc.2.

**Comment by Nancy-Salpepi** [comment] 2024-07-17 11:44
In the State wrapper when I follow similar steps to https://github.com/phetsims/gas-properties/issues/284#issue-2409582562, the downstream sim will launch with the correct average temperature after pressing Set State Now. 
If I then go back to the upstream sim and change the Number of Particles or the Radius and press Set State Now a second time, the average temperature will no longer match. 

Steps:
1. In the State Wrapper set state rate =0
2. In the upstream sim go to the Diffusion Screen
3. Add 20 blue particles
4. Increase the Mass to 30
5. Open the Data Panel
6. Press Set State Now -- average temperatures match
7. In the upstream sim change the radius to 125 (or add some more blue particles)
8. Press Set State Now -- average temperatures no longer match 
<img width="500" alt="Screenshot 2024-07-17 at 7 44 05 AM" src="https://github.com/user-attachments/assets/391aa6f6-a754-4f5a-80a2-93fe9f7371a7">

**Comment by pixelzoom** [comment] 2024-07-17 16:23
Reproduced in main.  

Noting that this workaround (first mentioned in https://github.com/phetsims/gas-properties/issues/284#issuecomment-2231790104) does NOT address this new problem.

```ts
    if ( assert && Tandem.PHET_IO_ENABLED ) {
      phet.phetio.phetioEngine.phetioStateEngine.stateSetEmitter.addListener( () => this.updateData() );
    }
```

**Comment by pixelzoom** [comment] 2024-07-17 17:27
This was indeed a serialization bug in DiffusionParticle1IO and DiffusionParticle2IO. While mass and radius were serialized correctly, there were not deserialized correctly.  The mass and radius values that were saved were not being used to create the particle instance during deserialization.  For example, here's the fix for DiffusionParticle1:

```diff
  /**
   * Deserializes an instance of DiffusionParticle1.
   */
  private static fromStateObject( stateObject: DiffusionParticle1StateObject ): DiffusionParticle1 {
    return new DiffusionParticle1( {
      x: stateObject.x,
      y: stateObject.y,
      previousX: stateObject._previousX,
      previousY: stateObject._previousY,
      vx: stateObject.vx,
-     vy: stateObject.vy
+     vy: stateObject.vy,
+     mass: stateObject.mass,
+     radius: stateObject.radius
    } );
  }
```

The primary commit is https://github.com/phetsims/gas-properties/commit/cab2dc59131c0a73d0165862c7f631e6f8cd26dd, the others are related to patching release branches for the 3 sims.

I tested both the original problem (https://github.com/phetsims/gas-properties/issues/284#issue-2409582562) and the more recent problem (https://github.com/phetsims/gas-properties/issues/284#issuecomment-2233117334).

@Nancy-Salpepi please test in main. Leave open for verification in 1.1.0-rc.2.

**Comment by pixelzoom** [comment] 2024-07-17 17:27
@Nancy-Salpepi please test in main. Leave open for verification in 1.1.0-rc.2.

**Comment by Nancy-Salpepi** [comment] 2024-07-17 19:52
This looks good now on main!

**Comment by pixelzoom** [comment] 2024-07-23 22:57
Please verify for https://github.com/phetsims/qa/issues/1125.  (This issue is irrelevant for the Gas Properties and Gases Intro sims.)

If everything looks OK, please close this issue.

**Closed** 2024-07-30 12:35 UTC
Labels: type:bug, dev:phet-io, status:ready-for-review
