### ISSUE TITLE
Blown lid not always stateful

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gas-properties#263] opened 2024-06-13 16:30 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari and Chrome

**Problem description**
In State and Studio wrappers, on the first 3 screens if the sim is launched after blowing the lid, the Standard Wrapper/Downstream sim will initially load showing the lid blowing animation, instead of the current state.

If the sim is paused before launching. The launched sim will load showing the lid on the container _and_ the Return Lid button.
Pressing play in the downstream sim and then pressing Set State Now a second time (after the blown lid is no longer visible), will result in the correct state loading. 

**Steps to reproduce**
1. In the State wrapper, set state rate = 0
2. On any of the first 3 screens add a lot of particles 
3. Add heat until the lid blows
4. Press Pause
5. Press Set State Now --in the downstream sim the lid is on the container and the Return Lid button is present
6. Press Play in the downstream sim --the lid blowing animation begins
7. Wait until the lid is offscreen in the downstream sim and then press Set State Now --the states will match

**Visuals**

https://github.com/phetsims/gas-properties/assets/87318828/2dff6a6a-964a-44b0-aeb1-3e255fcb1820

**Comment by pixelzoom** [comment] 2024-06-13 18:23
Nothing more fun than a state problem that involves animation! Thanks @Nancy-Salpepi :)

**Comment by pixelzoom** [comment] 2024-06-17 18:13
Reproduced with the Standard wrapper, where it's easier to debug.

1. Run the sim in Studio.
2. Go to Ideal screen (or Explore, Energy).
3. Add enough particles to cause the lid to blow off.
4. After the lid has left the screen, pause the sim. It will look something like the 1st screenshot below.
5. Press "Test" button in Studio to launch the Standard wrapper. It will look something like the 2nd screenshot below. Note that the lid is on the container, and the "Return Lid" button is visible.
6. Press the step button in the Standard wrapper. Note that the lid start to leave the container, as in the 3rd screenshot below.
7. Press the play button in the Standard wrapper. The lid will continue to animate, until it has left the screen.

<img width="782" alt="screenshot_3369" src="https://github.com/phetsims/gas-properties/assets/3046552/e9210075-202e-44ad-8e49-6512d20cb2d6">

<img width="999" alt="screenshot_3370" src="https://github.com/phetsims/gas-properties/assets/3046552/636e49e7-083c-44cd-b0fb-8df4598a4c88">

<img width="918" alt="screenshot_3371" src="https://github.com/phetsims/gas-properties/assets/3046552/0a9427e2-4860-40f5-b75e-36ab2b61530c">

**Comment by pixelzoom** [comment] 2024-06-17 18:21
The problem is that the lid's position and rotation are not stateful.  They are handled in IdealGasLawContainerNode `step`, relevant code shown below.  I'll need to add lidPositionProperty and lidRotationProperty, both instrumented.

```ts
  public step( dt: number ): void {
    assert && assert( dt >= 0, `invalid dt: ${dt}` );

    // Blow the lid off the container
    if ( !this.container.lidIsOnProperty.value && this.lidNode.visible ) {
      if ( this.visibleBoundsProperty.value.intersectsBounds( this.lidNode.bounds ) ) {

        // Lid is inside the visible bounds, animate it.
        const dx = LID_X_SPEED * dt;
        const dy = LID_Y_SPEED * dt;
        this.lidNode.centerX += dx;
        this.lidNode.centerY += dy;
        const dr = Utils.toRadians( LID_ROTATION_SPEED ) * dt;
        this.lidNode.rotateAround( this.lidNode.center, dr );
      }
      else {

        // Lid has left the visible bounds, hide it.
        this.lidNode.visible = false;
      }
    }
  }
```

**Comment by pixelzoom** [comment] 2024-06-17 19:56
As I'm trying to debug `lidHandleNode`, I'm running into a bit of code chaos that has accumulated as the result of PhET-iO instrumentation.  IdealGasLawContainerNode was getting too complicated, having to deal with internals of `resizeHandleNode` and `lidHandleNode`.  In https://github.com/phetsims/gas-properties/commit/92c3db2e538e3ddc8873bee109ed0f770bc41595, I moved Properties related to the handles into ResizeHandleNode.ts and LidHandleNode.ts.   This resulted in PhET-iO API changes - see Studio tree below. The end result is much cleaner and consistent.  And the code is in a better place for addressing this issue.

<img width="858" alt="screenshot_3372" src="https://github.com/phetsims/gas-properties/assets/3046552/985cc44c-e001-4a05-b4e0-0d971bca43d8">

**Comment by pixelzoom** [comment] 2024-06-17 20:59
Instrumenting `lidNode.visibleProperty` was a fair amount of work, which motivated the above API changes.  If you let the lid fully animate off the screen, the Standard wrapper will no longer showing the lid and the "Return Lid" buttons at the same time. 

What is still a problem is restoring state while the lid animation is in progress.  The lid's animated position is not stateful.  So if you (for example) launch the Standard wrapper while the lid animation is in progress, it will be displayed in the "lid on" position, along with the "Return Lid" button, and any particles that have already escaped from the container.

**Comment by pixelzoom** [comment] 2024-06-18 00:21
Making translation and rotation of the lid stateful was quite a project, requiring its own IOType so that we can control the order that translation and rotation are applied.  The animation behavior is a bit different now (which I cleared with @arouinfar in advance) but let me know if it looks wrong/odd.  Also be on the lookout for regressions. 

Addressing this issue required big changes. So I'd like to have both @Nancy-Salpepi and @arouinfar review.  If no problems are found, the last one assigned can close this issue.

**Comment by Nancy-Salpepi** [comment] 2024-06-18 16:30
This is working nicely for me @pixelzoom! I don't see any issues related to setting state with the lid blown.

**Comment by arouinfar** [comment] 2024-06-20 19:12
Looks good to me too @pixelzoom. State and tree changes all look good on main. Closing.

**Closed by arouinfar** 2024-06-20 19:12 UTC
Labels: type:bug, dev:phet-io, status:ready-for-review
