### ISSUE TITLE
CT: openingLeft 360 must be <= openingRight -2000

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#198] opened 2022-06-06 16:49 UTC
```
gases-intro : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/phet-io-wrappers/state/?sim=gases-intro&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gases-intro%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654397182046%7D
Uncaught Error: Uncaught Error: Assertion failed: openingLeft 360 must be <= openingRight -2000
Error: Assertion failed: openingLeft 360 must be <= openingRight -2000
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (IdealGasLawContainer.js:229:14)
at getOpeningLeft (IdealGasLawContainer.js:251:55)
at getOpeningWidth (IdealGasLawContainer.js:170:32)
at setWidth (IdealGasLawContainer.js:189:9)
at resizeImmediately (IdealGasLawModel.js:399:21)
at compensateForHoldConstant (IdealGasLawModel.js:339:9)
at updateModel (IdealGasLawModel.js:359:9)
at updateWhenPaused (IdealGasLawModel.js:136:15)
at callback (Multilink.ts:111:10)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM
```

**Comment by KatieWoe** [comment] 2022-09-09 22:48
Can you confirm if this issue is still needed? I don't see it in CT right now, but it is noted as rare. For https://github.com/phetsims/qa/issues/832

**Comment by pixelzoom** [comment] 2022-09-09 22:59
Yes, please keep this open.

**Comment by pixelzoom** [comment] 2022-11-29 01:02
Duplicate of https://github.com/phetsims/gas-properties/issues/108.

**Closed by pixelzoom** 2022-11-29 01:02 UTC
Labels: priority:5-deferred, type:automated-testing
